version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: opu-mariadb
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-allowed-packet=64M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11
    container_name: opu-flyway
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql:ro
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/${DB_NAME}
      FLYWAY_USER: ${FLYWAY_USER}
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
      FLYWAY_BASELINE_ON_MIGRATE: "true"
      FLYWAY_VALIDATE_ON_MIGRATE: "true"
    command: migrate

  redis:
    image: redis:7-alpine
    container_name: opu-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: opu-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: opu-alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: opu-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Seoul
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  alertmanager-discord:
    image: benjojo/alertmanager-discord
    container_name: opu-alertmanager-discord
    restart: always
    environment:
        - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1449442505417297964/6JCYgd5wGro-Seu8VHnDzp_zJVYoyKVW1nNYJ3Bi7mghh4Y1pUJe7WjBG9VWYE2UZse9

volumes:
  mariadb_data:
  redis_data:
  prometheus_data:
  grafana_data: