server:
  forward-headers-strategy: framework

spring:
  jackson:
    time-zone: Asia/Seoul
  profiles:
    active: dev
  application:
    name: opu-be
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    out-of-order: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      timeout: 2000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_SENDER_MAIL}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    email:
      secret: ${JWT_EMAIL_SECRET}
      expiration-minutes: 60
    password-reset:
      expiration-minutes: 15
    secret: ${JWT_SECRET}
    access-exp-sec: 1209600
    refresh-exp-sec: 1209600


  frontend-base-url: https://www.onepointup.site
  backend-base-url: http://ec2-13-209-4-254.ap-northeast-2.compute.amazonaws.com:8080

kakao:
  oauth:
    client-id: ${KAKAO_REST_API_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    admin-key: ${KAKAO_ADMIN_KEY}
    unlink-uri: https://kapi.kakao.com/v1/user/unlink

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}
    cloudfront-domain: ${AWS_CLOUDFRONT_DOMAIN}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

webpush:
    vapid:
      public-key: ${WEBPUSH_PUBLIC_KEY}
      private-key: ${WEBPUSH_PRIVATE_KEY}
      subject: ${WEBPUSH_SUBJECT}