global:
  resolve_timeout: 5m

route:
  receiver: "discord"
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1m

receivers:
  - name: "discord"
    webhook_configs:
      - url: "http://alertmanager-discord:9094"
        send_resolved: true