name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - deploy/172

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build jar
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # AWS 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 도커 빌드 및 푸시
      - name: Build & Push to ECR
        env:
          ECR_URI: ${{ secrets.ECR_URI }}
        run: |
          IMAGE_TAG=$(date +%Y%m%d-%H%M%S)
          docker build -t $ECR_URI:$IMAGE_TAG -t $ECR_URI:latest .
          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 8. Flyway 파일 변경 체크
      - name: Check Flyway SQL Changes
        id: migration
        run: |
          git fetch --depth=1 origin ${{ github.event.before }}
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "src/main/resources/db/migration/" || true)

          if [ -n "$CHANGED" ]; then
            echo "migration_changed=true" >> $GITHUB_OUTPUT
          else
            echo "migration_changed=false" >> $GITHUB_OUTPUT
          fi

#      변경된 경우에만 migration 파일 업로드
      - name: Upload Migration Files to EC2
        if: steps.migration.outputs.migration_changed == 'true'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "src/main/resources/db/migration/*"
          target: "/home/ec2-user/app/src/main/resources/db/migration/"


      # EC2 접속하여 자동 재배포
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        env:
          image: ${{ secrets.ECR_URI }}:${{ env.IMAGE_TAG }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # aws 권한 받을 시 삭제
          script: |
            export IMAGE_TAG=${{ env.IMAGE_TAG }}
            
            cd /home/ec2-user/app
            
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
              | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

            TAG=${{ env.IMAGE_TAG }}
            sed -i "s#image: .*#image: ${{ secrets.ECR_URI }}:$TAG#g" docker-compose.yml
                    
            docker-compose -f docker-compose.app.yml up -d

#           Flyway 조건 실행
            if [ "${{ steps.migration.outputs.migration_changed }}" = "true" ]; then
              echo "Flyway migration detected. Running migration..."
              docker-compose -f docker-compose.flyway.yml run --rm flyway
            else
              echo "No Flyway migration changes. Skipping."
            fi
            
            docker image prune -f --filter until=72h
